/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Review = IDL.Record({
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Category = IDL.Variant({
  'chaat' : IDL.Null,
  'soup' : IDL.Null,
  'sandwich' : IDL.Null,
  'fastFood' : IDL.Null,
  'friesSnacks' : IDL.Null,
  'tandoori' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : Category,
  'price' : IDL.Nat,
});
export const RestaurantInfo = IDL.Record({
  'instagram' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getMenuByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Review = IDL.Record({
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'chaat' : IDL.Null,
    'soup' : IDL.Null,
    'sandwich' : IDL.Null,
    'fastFood' : IDL.Null,
    'friesSnacks' : IDL.Null,
    'tandoori' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const RestaurantInfo = IDL.Record({
    'instagram' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getMenuByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };